/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.abf.client;

import org.openide.util.NbBundle;

import de.cismet.cids.abf.librarysupport.project.customizer.PropertyProvider;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  1.3
 */
public final class DeployVisualPanel extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    private final transient PropertyProvider provider;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final transient javax.swing.ButtonGroup bgLegacyDeploy = new javax.swing.ButtonGroup();
    private final transient javax.swing.Box.Filler filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0),
            new java.awt.Dimension(0, 0),
            new java.awt.Dimension(0, 32767));
    private final transient javax.swing.Box.Filler filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0),
            new java.awt.Dimension(0, 0),
            new java.awt.Dimension(32767, 0));
    private final transient javax.swing.JPanel pnlChooseLibUse = new javax.swing.JPanel();
    private final transient javax.swing.JRadioButton rdbDirectLibUse = new javax.swing.JRadioButton();
    private final transient javax.swing.JRadioButton rdbServiceLibUse = new javax.swing.JRadioButton();
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form DeployVisualPanel.
     *
     * @param  project  DOCUMENT ME!
     */
    public DeployVisualPanel(final ClientProject project) {
        provider = PropertyProvider.getInstance(project.getProjectProperties());
        assert provider != null;

        initComponents();

        init();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     */
    private void init() {
        final String strategy = provider.get(PropertyProvider.KEY_DEPLOYMENT_STRATEGY);
        if (PropertyProvider.STRATEGY_USE_LOCAL.equals(strategy)) {
            rdbDirectLibUse.setSelected(true);
        } else if (PropertyProvider.STRATEGY_USE_SIGN_SERVICE.equals(strategy)) {
            rdbServiceLibUse.setSelected(true);
        } else {
            // strategy unset, this is default
            rdbDirectLibUse.setSelected(true);
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     *
     * @throws  IllegalStateException  DOCUMENT ME!
     */
    String getStrategy() {
        if (rdbDirectLibUse.isSelected()) {
            return PropertyProvider.STRATEGY_USE_LOCAL;
        } else if (rdbServiceLibUse.isSelected()) {
            return PropertyProvider.STRATEGY_USE_SIGN_SERVICE;
        } else {
            throw new IllegalStateException("unknown selection, update implementation!"); // NOI18N
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        pnlChooseLibUse.setBorder(javax.swing.BorderFactory.createTitledBorder(
                NbBundle.getMessage(DeployVisualPanel.class, "DeployVisualPanel.pnlChooseLibStrategy.border.title"))); // NOI18N
        pnlChooseLibUse.setOpaque(false);
        pnlChooseLibUse.setLayout(new java.awt.GridBagLayout());

        bgLegacyDeploy.add(rdbDirectLibUse);
        rdbDirectLibUse.setText(NbBundle.getMessage(DeployVisualPanel.class, "DeployVisualPanel.rdbDirectLibUse.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlChooseLibUse.add(rdbDirectLibUse, gridBagConstraints);

        bgLegacyDeploy.add(rdbServiceLibUse);
        rdbServiceLibUse.setText(NbBundle.getMessage(
                DeployVisualPanel.class,
                "DeployVisualPanel.rdbServiceLibUse.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlChooseLibUse.add(rdbServiceLibUse, gridBagConstraints);

        filler2.setMaximumSize(new java.awt.Dimension(32767, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        pnlChooseLibUse.add(filler2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(pnlChooseLibUse, gridBagConstraints);

        filler1.setMaximumSize(new java.awt.Dimension(0, 32767));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        add(filler1, gridBagConstraints);
    } // </editor-fold>//GEN-END:initComponents
}
