/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 *  Copyright (C) 2010 mscholl
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.cismet.cids.abf.distribution;

import org.apache.maven.artifact.Artifact;

import org.openide.util.NbBundle;

import java.awt.Component;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 * DOCUMENT ME!
 *
 * @version  $Revision$, $Date$
 */
public final class EditDistributionVisualPanel1 extends JPanel {

    //~ Static fields/initializers ---------------------------------------------

    /** Use serialVersionUID for interoperability. */
    private static final long serialVersionUID = 3196389420902075341L;

    //~ Instance fields --------------------------------------------------------

    private final EditDistributionWizardPanel1 model;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlApps;
    // End of variables declaration//GEN-END:variables

    private transient List<Artifact> availableApps;

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form EditDistributionVisualPanel1.
     *
     * @param  model  DOCUMENT ME!
     */
    public EditDistributionVisualPanel1(final EditDistributionWizardPanel1 model) {
        this.model = model;
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     */
    void init() {
        pnlApps.removeAll();

        availableApps = (List<Artifact>)new ArrayList(model.getMavenProject().getDependencyArtifacts());
        Collections.sort(availableApps, new Comparator<Artifact>() {

                @Override
                public int compare(final Artifact o1, final Artifact o2) {
                    return o1.getArtifactId().compareTo(o2.getArtifactId());
                }
            });

        final List<Artifact> selectedApps = model.getSelectedAppNames();

        for (final Artifact dependency : availableApps) {
            if (!dependency.getScope().equalsIgnoreCase("test")) { // NOI18N
                final JCheckBox checkbox = new JCheckBox(dependency.getArtifactId());
                checkbox.setSelected((selectedApps == null) ? true : selectedApps.contains(dependency));
                checkbox.addChangeListener(new ChangeListener() {

                        @Override
                        public void stateChanged(final ChangeEvent e) {
                            model.fireChangeEvent();
                        }
                    });
                pnlApps.add(checkbox);
            }
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    List<Artifact> getSelectedApps() {
        final List<Artifact> apps = new ArrayList<Artifact>();

        for (final Component component : pnlApps.getComponents()) {
            if (component instanceof JCheckBox) {
                final JCheckBox box = (JCheckBox)component;
                if (box.isSelected()) {
                    for (final Artifact artifact : availableApps) {
                        if (artifact.getArtifactId().equals(box.getText())) {
                            apps.add(artifact);
                        }
                    }
                }
            }
        }

        return apps;
    }

    @Override
    public String getName() {
        return NbBundle.getMessage(
                EditDistributionVisualPanel1.class,
                "EditDistributionVisualPanel1.getName().returnValue"); // NOI18N
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        pnlApps = new javax.swing.JPanel();

        pnlApps.setBorder(javax.swing.BorderFactory.createTitledBorder(
                NbBundle.getMessage(
                    EditDistributionVisualPanel1.class,
                    "EditDistributionVisualPanel1.pnlApps.border.title"))); // NOI18N
        pnlApps.setLayout(new javax.swing.BoxLayout(pnlApps, javax.swing.BoxLayout.PAGE_AXIS));

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap().addComponent(
                    pnlApps,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    275,
                    Short.MAX_VALUE).addContainerGap()));
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap().addComponent(
                    pnlApps,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    241,
                    Short.MAX_VALUE).addContainerGap()));
    } // </editor-fold>//GEN-END:initComponents
}
