/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.abf.librarysupport.project.nodes.wizard;

import org.openide.util.WeakListeners;

import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  1.1
 */
public final class NewJarVisualPanel extends JPanel {

    //~ Instance fields --------------------------------------------------------

    private final transient DocumentListener docL;
    private final transient NewJarWizardPanel model;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final transient javax.swing.JLabel lblName = new javax.swing.JLabel();
    private final transient javax.swing.JTextField txtName = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new NewJarVisualPanel object.
     *
     * @param  model  DOCUMENT ME!
     */
    public NewJarVisualPanel(final NewJarWizardPanel model) {
        this.model = model;
        docL = new DocumentListenerImpl();
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     */
    void init() {
        txtName.getDocument().addDocumentListener(WeakListeners.document(docL, txtName.getDocument()));
        txtName.setText(org.openide.util.NbBundle.getMessage(
                NewJarVisualPanel.class,
                "NewJarVisualPanel.txtName.text")); // NOI18N
        txtName.setSelectionStart(0);
        txtName.setSelectionEnd(txtName.getText().length());
    }

    @Override
    public String getName() {
        return org.openide.util.NbBundle.getMessage(
                NewJarVisualPanel.class,
                "NewJarVisualPanel.getName().returnvalue"); // NOI18N
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    String getJarName() {
        return txtName.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        org.openide.awt.Mnemonics.setLocalizedText(
            lblName,
            org.openide.util.NbBundle.getMessage(NewJarVisualPanel.class, "NewJarVisualPanel.lblName.text")); // NOI18N

        final org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(lblName).addPreferredGap(
                    org.jdesktop.layout.LayoutStyle.RELATED,
                    34,
                    Short.MAX_VALUE).add(
                    txtName,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                    561,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap()));
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(lblName).add(
                        txtName,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addContainerGap(419, Short.MAX_VALUE)));
    } // </editor-fold>//GEN-END:initComponents

    //~ Inner Classes ----------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private final class DocumentListenerImpl implements DocumentListener {

        //~ Methods ------------------------------------------------------------

        @Override
        public void changedUpdate(final DocumentEvent documentEvent) {
            model.fireChangeEvent();
        }

        @Override
        public void insertUpdate(final DocumentEvent documentEvent) {
            model.fireChangeEvent();
        }

        @Override
        public void removeUpdate(final DocumentEvent documentEvent) {
            model.fireChangeEvent();
        }
    }
}
