/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.abf.librarysupport.project.nodes.wizard;

import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  1.5
 */
public final class RenameManifestVisualPanel1 extends JPanel implements DocumentListener {

    //~ Instance fields --------------------------------------------------------

    private final transient RenameManifestWizardPanel1 model;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final transient javax.swing.JSeparator jSeparator2 = new javax.swing.JSeparator();
    private final transient javax.swing.JLabel lblNewName = new javax.swing.JLabel();
    private final transient javax.swing.JTextField txtNewName = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new RenameManifestVisualPanel1 object.
     *
     * @param  model  DOCUMENT ME!
     */
    public RenameManifestVisualPanel1(final RenameManifestWizardPanel1 model) {
        this.model = model;
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     */
    void init() {
        txtNewName.setText(model.getManifest().getName());
        txtNewName.setSelectionStart(txtNewName.getText().indexOf(
                model.getManifest().getName()));
        txtNewName.setSelectionEnd(txtNewName.getText().length());
        txtNewName.getDocument().addDocumentListener(this);
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    String getNewManifestName() {
        return txtNewName.getText();
    }

    @Override
    public String getName() {
        return org.openide.util.NbBundle.getMessage(
                RenameManifestVisualPanel1.class,
                "Dsc_name"); // NOI18N
    }

    @Override
    public void insertUpdate(final DocumentEvent documentEvent) {
        changedUpdate(documentEvent);
    }

    @Override
    public void removeUpdate(final DocumentEvent documentEvent) {
        changedUpdate(documentEvent);
    }

    @Override
    public void changedUpdate(final DocumentEvent documentEvent) {
        model.fireChangeEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        org.openide.awt.Mnemonics.setLocalizedText(
            lblNewName,
            org.openide.util.NbBundle.getMessage(
                RenameManifestVisualPanel1.class,
                "RenameManifestVisualPanel1.lblNewName.text")); // NOI18N

        final org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                        org.jdesktop.layout.GroupLayout.TRAILING,
                        layout.createSequentialGroup().add(lblNewName).add(48, 48, 48).add(
                            txtNewName,
                            org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                            628,
                            Short.MAX_VALUE)).add(
                        jSeparator2,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        748,
                        Short.MAX_VALUE)).addContainerGap()));
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(lblNewName).add(
                        txtNewName,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                    org.jdesktop.layout.LayoutStyle.RELATED).add(
                    jSeparator2,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                    10,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap(308, Short.MAX_VALUE)));
    } // </editor-fold>//GEN-END:initComponents
}
