/*
 * NewUserVisualPanel2.java, encoding: UTF-8
 *
 * Copyright (C) by:
 *
 *----------------------------
 * cismet GmbH
 * Altenkesslerstr. 17
 * Gebaeude D2
 * 66115 Saarbruecken
 * http://www.cismet.de
 *----------------------------
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * See: http://www.gnu.org/licenses/lgpl.txt
 *
 *----------------------------
 * Author:
 * martin.scholl@cismet.de
 *----------------------------
 *
 * Created on ???
 *
 */

package de.cismet.cids.abf.domainserver.project.users;

import de.cismet.cids.abf.domainserver.project.utils.ProjectUtils;
import de.cismet.cids.abf.domainserver.project.utils.Renderers;
import de.cismet.cids.jpa.entity.user.UserGroup;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;

public final class NewUserVisualPanel2 extends JPanel
{
    private final transient NewUserWizardPanel2 model;

    public NewUserVisualPanel2(final NewUserWizardPanel2 model)
    {
        this.model = model;
        initComponents();
    }
    
    void init()
    {
        final List<UserGroup> l = model.getProject().getCidsDataObjectBackend().
                getAllEntities(UserGroup.class);
        final List<UserGroup> groups = new ArrayList<UserGroup>();
        for(final UserGroup ug : l)
        {
            if(!ProjectUtils.isRemoteGroup(ug, model.getProject()))
            {
                groups.add(ug);
            }
        }
        lstGroup.setCellRenderer(new Renderers.UserGroupListRenderer(model.
                getProject()));
        lstGroup.setSelectionMode(ListSelectionModel.
                MULTIPLE_INTERVAL_SELECTION);
        lstGroup.setListData(groups.toArray());
    }
    
    List<UserGroup> getUserGroups()
    {
        final Object[] values = lstGroup.getSelectedValues();
        final List<UserGroup> l = new ArrayList<UserGroup>(values.length);
        for(final Object o : values)
        {
            l.add((UserGroup)o);
        }
        return l;
    }
    
    @Override
    public String getName()
    {
        return org.openide.util.NbBundle.getMessage(
                NewUserVisualPanel2.class, "NewUserVisualPanel2.getName().returnvalue"); // NOI18N
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1.setViewportView(lstGroup);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 346, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final transient javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    private final transient javax.swing.JList lstGroup = new javax.swing.JList();
    // End of variables declaration//GEN-END:variables
}