/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.abf.domainserver.project.users;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JPanel;
import javax.swing.ListSelectionModel;

import de.cismet.cids.abf.domainserver.project.utils.ProjectUtils;
import de.cismet.cids.abf.domainserver.project.utils.Renderers;

import de.cismet.cids.jpa.entity.user.UserGroup;

/**
 * DOCUMENT ME!
 *
 * @version  $Revision$, $Date$
 */
public final class NewUserVisualPanel2 extends JPanel {

    //~ Instance fields --------------------------------------------------------

    private final transient NewUserWizardPanel2 model;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final transient javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    private final transient javax.swing.JList lstGroup = new javax.swing.JList();
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new NewUserVisualPanel2 object.
     *
     * @param  model  DOCUMENT ME!
     */
    public NewUserVisualPanel2(final NewUserWizardPanel2 model) {
        this.model = model;
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     */
    void init() {
        final List<UserGroup> l = model.getProject().getCidsDataObjectBackend().getAllEntities(UserGroup.class);
        final List<UserGroup> groups = new ArrayList<UserGroup>();
        for (final UserGroup ug : l) {
            if (!ProjectUtils.isRemoteGroup(ug, model.getProject())) {
                groups.add(ug);
            }
        }
        lstGroup.setCellRenderer(new Renderers.UserGroupListRenderer(model.getProject()));
        lstGroup.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        lstGroup.setListData(groups.toArray());
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    List<UserGroup> getUserGroups() {
        final Object[] values = lstGroup.getSelectedValues();
        final List<UserGroup> l = new ArrayList<UserGroup>(values.length);
        for (final Object o : values) {
            l.add((UserGroup)o);
        }
        return l;
    }

    @Override
    public String getName() {
        return org.openide.util.NbBundle.getMessage(
                NewUserVisualPanel2.class,
                "NewUserVisualPanel2.getName().returnvalue"); // NOI18N
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1.setViewportView(lstGroup);

        final org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                org.jdesktop.layout.GroupLayout.TRAILING,
                layout.createSequentialGroup().addContainerGap(44, Short.MAX_VALUE).add(
                    jScrollPane1,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                    346,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap()));
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    jScrollPane1,
                    org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                    278,
                    Short.MAX_VALUE).addContainerGap()));
    } // </editor-fold>//GEN-END:initComponents
}
