/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.abf.domainserver.project.users;

import org.openide.util.WeakListeners;

import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import de.cismet.cids.jpa.entity.user.User;

/**
 * DOCUMENT ME!
 *
 * @author   martin.scholl@cismet.de
 * @version  $Revision$, $Date$
 */
public final class NewUserVisualPanel1 extends JPanel {

    //~ Instance fields --------------------------------------------------------

    private final transient NewUserWizardPanel1 model;
    private final transient DocumentListener docL;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final transient javax.swing.JCheckBox chkAdmin = new javax.swing.JCheckBox();
    private final transient javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
    private final transient javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
    private final transient javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
    private final transient javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
    private final transient javax.swing.JLabel lblDomainserver = new javax.swing.JLabel();
    private final transient javax.swing.JTextField txtLogin = new javax.swing.JTextField();
    private final transient javax.swing.JTextField txtPass = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new NewUserVisualPanel1 object.
     *
     * @param  model  DOCUMENT ME!
     */
    public NewUserVisualPanel1(final NewUserWizardPanel1 model) {
        this.model = model;
        docL = new DocumentListenerImpl();
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     */
    void init() {
        clearFields();
        lblDomainserver.setText(model.getDomainserverName());
        txtPass.getDocument().addDocumentListener(
            WeakListeners.document(docL, txtPass.getDocument()));
        txtLogin.getDocument().addDocumentListener(
            WeakListeners.document(docL, txtLogin.getDocument()));
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    User getUser() {
        final User user = new User();
        user.setLoginname(txtLogin.getText());
        user.setPassword(txtPass.getText());
        user.setAdmin(chkAdmin.isSelected());
        return user;
    }

    /**
     * DOCUMENT ME!
     */
    public void clearFields() {
        txtLogin.setText("");        // NOI18N
        txtPass.setText("");         // NOI18N
        chkAdmin.setSelected(false);
        lblDomainserver.setText(""); // NOI18N
    }

    @Override
    public String getName() {
        return org.openide.util.NbBundle.getMessage(
                NewUserVisualPanel1.class,
                "NewUserVisualPanel1.getName().returnvalue"); // NOI18N
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        chkAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        org.openide.awt.Mnemonics.setLocalizedText(
            jLabel2,
            org.openide.util.NbBundle.getMessage(NewUserVisualPanel1.class, "NewUserVisualPanel1.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(
            jLabel3,
            org.openide.util.NbBundle.getMessage(NewUserVisualPanel1.class, "NewUserVisualPanel1.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(
            jLabel4,
            org.openide.util.NbBundle.getMessage(NewUserVisualPanel1.class, "NewUserVisualPanel1.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(
            jLabel5,
            org.openide.util.NbBundle.getMessage(NewUserVisualPanel1.class, "NewUserVisualPanel1.jLabel5.text")); // NOI18N

        final org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(jLabel2).add(jLabel3).add(
                        jLabel4).add(jLabel5)).add(103, 103, 103).add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(chkAdmin).add(
                        txtLogin,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        207,
                        Short.MAX_VALUE).add(lblDomainserver).add(
                        txtPass,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        207,
                        Short.MAX_VALUE)).addContainerGap()));
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(lblDomainserver).add(
                        jLabel2)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(
                        txtLogin,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(jLabel3)).addPreferredGap(
                    org.jdesktop.layout.LayoutStyle.RELATED).add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(
                        txtPass,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(jLabel4)).addPreferredGap(
                    org.jdesktop.layout.LayoutStyle.RELATED).add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(chkAdmin).add(jLabel5))
                            .addContainerGap(205, Short.MAX_VALUE)));
    } // </editor-fold>//GEN-END:initComponents

    //~ Inner Classes ----------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private final class DocumentListenerImpl implements DocumentListener {

        //~ Methods ------------------------------------------------------------

        @Override
        public void changedUpdate(final DocumentEvent e) {
            model.fireChangeEvent();
        }

        @Override
        public void removeUpdate(final DocumentEvent e) {
            changedUpdate(e);
        }

        @Override
        public void insertUpdate(final DocumentEvent e) {
            changedUpdate(e);
        }
    }
}
