/*
 * NewUserVisualPanel1.java, encoding: UTF-8
 *
 * Copyright (C) by:
 *
 *----------------------------
 * cismet GmbH
 * Altenkesslerstr. 17
 * Gebaeude D2
 * 66115 Saarbruecken
 * http://www.cismet.de
 *----------------------------
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * See: http://www.gnu.org/licenses/lgpl.txt
 *
 *----------------------------
 * Author:
 * martin.scholl@cismet.de
 *----------------------------
 *
 * Created on ???
 *
 */

package de.cismet.cids.abf.domainserver.project.users;

import de.cismet.cids.jpa.entity.user.User;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.util.WeakListeners;

/**
 *
 * @author martin.scholl@cismet.de
 */
public final class NewUserVisualPanel1 extends JPanel
{
    private final transient NewUserWizardPanel1 model;
    private final transient DocumentListener docL;
    
    public NewUserVisualPanel1(final NewUserWizardPanel1 model)
    {
        this.model = model;
        docL = new DocumentListenerImpl();
        initComponents();
    }
    
    void init()
    {
        clearFields();
        lblDomainserver.setText(model.getDomainserverName());
        txtPass.getDocument().addDocumentListener(
                WeakListeners.document(docL, txtPass.getDocument()));
        txtLogin.getDocument().addDocumentListener(
                WeakListeners.document(docL, txtLogin.getDocument()));
    }
    
    User getUser()
    {
        final User user = new User();
        user.setLoginname(txtLogin.getText());
        user.setPassword(txtPass.getText());
        user.setAdmin(chkAdmin.isSelected());
        return user;
    }
    
    public void clearFields()
    {
        txtLogin.setText(""); // NOI18N
        txtPass.setText(""); // NOI18N
        chkAdmin.setSelected(false);
        lblDomainserver.setText(""); // NOI18N
    }
    
    @Override
    public String getName()
    {
        return org.openide.util.NbBundle.getMessage(
                NewUserVisualPanel1.class, "NewUserVisualPanel1.getName().returnvalue"); // NOI18N
    }
    
    private final class DocumentListenerImpl implements DocumentListener
    {
        @Override
        public void changedUpdate(final DocumentEvent e)
        {
            model.fireChangeEvent();
        }

        @Override
        public void removeUpdate(final DocumentEvent e)
        {
            changedUpdate(e);
        }

        @Override
        public void insertUpdate(final DocumentEvent e)
        {
            changedUpdate(e);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(NewUserVisualPanel1.class, "NewUserVisualPanel1.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(NewUserVisualPanel1.class, "NewUserVisualPanel1.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(NewUserVisualPanel1.class, "NewUserVisualPanel1.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(NewUserVisualPanel1.class, "NewUserVisualPanel1.jLabel5.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(jLabel5))
                .add(103, 103, 103)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(chkAdmin)
                    .add(txtLogin, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .add(lblDomainserver)
                    .add(txtPass, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblDomainserver)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtPass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(chkAdmin)
                    .add(jLabel5))
                .addContainerGap(205, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final transient javax.swing.JCheckBox chkAdmin = new javax.swing.JCheckBox();
    private final transient javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
    private final transient javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
    private final transient javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
    private final transient javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
    private final transient javax.swing.JLabel lblDomainserver = new javax.swing.JLabel();
    private final transient javax.swing.JTextField txtLogin = new javax.swing.JTextField();
    private final transient javax.swing.JTextField txtPass = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}