/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.abf.librarysupport.project.nodes.wizard;

import org.openide.filesystems.FileObject;

import java.io.File;

import java.util.Collections;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

import de.cismet.cids.abf.utilities.files.PackageUtils;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  1.6
 */
public final class AddFilesVisualPanel1 extends JPanel {

    //~ Instance fields --------------------------------------------------------

    private final transient FileObject root;
    private final transient FileObject current;
    private final transient DefaultComboBoxModel model;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final transient javax.swing.JComboBox cboPackage = new javax.swing.JComboBox();
    private final transient javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    private final transient javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
    private final transient javax.swing.JLabel lblPackage = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form AddFilesVisualPanel1.
     *
     * @param  root     DOCUMENT ME!
     * @param  current  DOCUMENT ME!
     */
    public AddFilesVisualPanel1(final FileObject root, final FileObject current) {
        this.root = root;
        this.current = current;
        initComponents();
        final List<String> packages = getPackages(root);
        model = new DefaultComboBoxModel(packages.toArray());
        init();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     */
    public void init() {
        model.setSelectedItem(PackageUtils.toPackage(root, current));
        cboPackage.setModel(model);
        fileChooser.setDragEnabled(false);
        fileChooser.setCurrentDirectory(new File(System.getProperty(
                    "user.home"))); // NOI18N
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fileChooser.setMultiSelectionEnabled(true);
    }

    /**
     * DOCUMENT ME!
     *
     * @param   root  DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    private List<String> getPackages(final FileObject root) {
        final LinkedList<String> packages = new LinkedList<String>();
        for (final Enumeration<? extends FileObject> e = root.getFolders(true); e.hasMoreElements();) {
            packages.add(PackageUtils.toPackage(root, e.nextElement()));
        }
        Collections.sort(packages);
        packages.addFirst("<root>"); // NOI18N
        return packages;
    }

    @Override
    public String getName() {
        return org.openide.util.NbBundle.getMessage(
                AddFilesVisualPanel1.class,
                "AddFilesVisualPanel.getName().returnvalue"); // NOI18N
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public File[] getChoosenFiles() {
        return fileChooser.getSelectedFiles();
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public String getChoosenPackage() {
        return model.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        fileChooser.setControlButtonsAreShown(false);

        org.openide.awt.Mnemonics.setLocalizedText(
            lblPackage,
            org.openide.util.NbBundle.getMessage(AddFilesVisualPanel1.class, "AddFilesVisualPanel.lblPackage.text")); // NOI18N

        final org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                        fileChooser,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        649,
                        Short.MAX_VALUE).add(
                        layout.createSequentialGroup().add(lblPackage).addPreferredGap(
                            org.jdesktop.layout.LayoutStyle.RELATED).add(cboPackage, 0, 506, Short.MAX_VALUE)))
                            .addContainerGap()).add(
                jSeparator1,
                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                673,
                Short.MAX_VALUE));
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    fileChooser,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                    org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(32, 32, 32).add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(lblPackage).add(
                        cboPackage,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                    org.jdesktop.layout.LayoutStyle.RELATED).add(
                    jSeparator1,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                    10,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap(56, Short.MAX_VALUE)));
    } // </editor-fold>//GEN-END:initComponents
}
