/*
 * AddFilesVisualPanel1.java, encoding: UTF-8
 *
 * Copyright (C) by:
 *
 *----------------------------
 * cismet GmbH
 * Altenkesslerstr. 17
 * Gebaeude D2
 * 66115 Saarbruecken
 * http://www.cismet.de
 *----------------------------
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * See: http://www.gnu.org/licenses/lgpl.txt
 *
 *----------------------------
 * Author:
 * martin.scholl@cismet.de
 *----------------------------
 *
 * Created on ???
 *
 */

package de.cismet.cids.abf.librarysupport.project.nodes.wizard;

import de.cismet.cids.abf.utilities.files.PackageUtils;
import java.io.File;
import java.util.Collections;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import org.openide.filesystems.FileObject;

/**
 *
 * @author mscholl
 * @version 1.6
 */
public final class AddFilesVisualPanel1 extends JPanel
{
    private final transient FileObject root;
    private final transient FileObject current;
    private final transient DefaultComboBoxModel model;
    
    /** Creates new form AddFilesVisualPanel1 */
    public AddFilesVisualPanel1(final FileObject root, final FileObject current)
    {
        this.root = root;
        this.current = current;
        initComponents();
        final List<String> packages = getPackages(root);
        model = new DefaultComboBoxModel(packages.toArray());
        init();
    }
    
    public void init()
    {
        model.setSelectedItem(PackageUtils.toPackage(root, current));
        cboPackage.setModel(model);
        fileChooser.setDragEnabled(false);
        fileChooser.setCurrentDirectory(new File(System.getProperty(
                "user.home"))); // NOI18N
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fileChooser.setMultiSelectionEnabled(true);
    }

    private List<String> getPackages(final FileObject root)
    {
        final LinkedList<String> packages = new LinkedList<String>();
        for(final Enumeration<? extends FileObject> e = root.getFolders(true);
                e.hasMoreElements();)
        {
            packages.add(PackageUtils.toPackage(root, e.nextElement()));
        }
        Collections.sort(packages);
        packages.addFirst("<root>"); // NOI18N
        return packages;
    }
    
    @Override
    public String getName()
    {
        return org.openide.util.NbBundle.getMessage(
                AddFilesVisualPanel1.class, "Dsc_addFiles");// NOI18N
    }
    
    public File[] getChoosenFiles()
    {
        return fileChooser.getSelectedFiles();
    }
    
    public String getChoosenPackage()
    {
        return model.getSelectedItem().toString();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser.setControlButtonsAreShown(false);

        org.openide.awt.Mnemonics.setLocalizedText(lblPackage, org.openide.util.NbBundle.getMessage(AddFilesVisualPanel1.class, "Lbl_addToThisPackage")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(fileChooser, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(lblPackage)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cboPackage, 0, 464, Short.MAX_VALUE)))
                .addContainerGap())
            .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(fileChooser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(32, 32, 32)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblPackage)
                    .add(cboPackage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final transient javax.swing.JComboBox cboPackage = new javax.swing.JComboBox();
    private final transient javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    private final transient javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
    private final transient javax.swing.JLabel lblPackage = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
    
}

