/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.abf.librarysupport.project.nodes.wizard;

import javax.swing.JPanel;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  1.2
 */
public final class NewVisualPanel1 extends JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final transient javax.swing.JTextPane TxpDescription = new javax.swing.JTextPane();
    private final transient javax.swing.JComboBox cboPackage = new javax.swing.JComboBox();
    private final transient javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    private final transient javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
    private final transient javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
    private final transient javax.swing.JLabel lblDescription = new javax.swing.JLabel();
    private final transient javax.swing.JLabel lblPackage = new javax.swing.JLabel();
    private final transient javax.swing.JLabel lblTypes = new javax.swing.JLabel();
    private final transient javax.swing.JList lstTypes = new javax.swing.JList();
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form NewVisualPanel1.
     */
    public NewVisualPanel1() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    @Override
    public String getName() {
        return org.openide.util.NbBundle.getMessage(NewVisualPanel1.class,
                "NewVisualPanel1.getName().returnvalue"); // NOI18N
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        org.openide.awt.Mnemonics.setLocalizedText(
            lblPackage,
            org.openide.util.NbBundle.getMessage(NewVisualPanel1.class, "NewVisualPanel1.lblPackage.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(
            lblTypes,
            org.openide.util.NbBundle.getMessage(NewVisualPanel1.class, "NewVisualPanel1.lblTypes.text")); // NOI18N

        jScrollPane1.setViewportView(lstTypes);

        org.openide.awt.Mnemonics.setLocalizedText(
            lblDescription,
            org.openide.util.NbBundle.getMessage(NewVisualPanel1.class, "NewVisualPanel1.lblDescription.text")); // NOI18N

        jScrollPane2.setViewportView(TxpDescription);

        final org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                        jSeparator1,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        775,
                        Short.MAX_VALUE).add(
                        layout.createSequentialGroup().add(
                            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(lblTypes).add(
                                jScrollPane1,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                364,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                            org.jdesktop.layout.LayoutStyle.RELATED,
                            55,
                            Short.MAX_VALUE).add(
                            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                                lblDescription).add(
                                jScrollPane2,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                356,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))).add(
                        layout.createSequentialGroup().add(lblPackage).addPreferredGap(
                            org.jdesktop.layout.LayoutStyle.RELATED).add(cboPackage, 0, 705, Short.MAX_VALUE)))
                            .addContainerGap()));
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(lblPackage).add(
                        cboPackage,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).add(26, 26, 26).add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(lblTypes).add(
                        lblDescription)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false).add(jScrollPane2).add(
                        jScrollPane1,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        188,
                        Short.MAX_VALUE)).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
                    jSeparator1,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                    10,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap(67, Short.MAX_VALUE)));
    } // </editor-fold>//GEN-END:initComponents
}
