/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.abf.domainserver.project.catalog;

import org.openide.explorer.propertysheet.editors.EnhancedCustomPropertyEditor;

import javax.swing.JEditorPane;
import javax.swing.text.EditorKit;

/**
 * DOCUMENT ME!
 *
 * @author   martin.scholl@cismet.de
 * @version  $Revision$, $Date$
 */
public class DynamicChildrenSimpleEditor extends javax.swing.JPanel implements EnhancedCustomPropertyEditor // TODO: using depricated api here...
{

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final transient javax.swing.JEditorPane edpDynChild = new javax.swing.JEditorPane();
    private final transient javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new DynamicChildrenSimpleEditor object.
     *
     * @param  statement  DOCUMENT ME!
     * @param  editable   DOCUMENT ME!
     */
    public DynamicChildrenSimpleEditor(final String statement,
            final boolean editable) {
        initComponents();
        init();
        edpDynChild.setText(statement);
        edpDynChild.setEditable(editable);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    String getStatement() {
        return edpDynChild.getText();
    }

    /**
     * DOCUMENT ME!
     */
    private void init() {
        edpDynChild.setContentType("text/x-sql");                                      // NOI18N
        final EditorKit kit = JEditorPane.createEditorKitForContentType("text/x-sql"); // NOI18N
        kit.install(edpDynChild);
        edpDynChild.setEditorKit(kit);
    }

    @Override
    public Object getPropertyValue() throws IllegalStateException {
        return getStatement();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1.setViewportView(edpDynChild);

        final org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    jScrollPane1,
                    org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                    398,
                    Short.MAX_VALUE).addContainerGap()));
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    jScrollPane1,
                    org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                    344,
                    Short.MAX_VALUE).addContainerGap()));
    } // </editor-fold>//GEN-END:initComponents
}
