/*
 * DynamicChildrenSimpleEditor.java, encoding: UTF-8
 *
 * Copyright (C) by:
 *
 *----------------------------
 * cismet GmbH
 * Altenkesslerstr. 17
 * Gebaeude D2
 * 66115 Saarbruecken
 * http://www.cismet.de
 *----------------------------
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * See: http://www.gnu.org/licenses/lgpl.txt
 *
 *----------------------------
 * Author:
 * martin.scholl@cismet.de
 *----------------------------
 *
 * Created on 27. November 2007, 08:11
 *
 */

package de.cismet.cids.abf.domainserver.project.catalog;

import javax.swing.JEditorPane;
import javax.swing.text.EditorKit;
import org.openide.explorer.propertysheet.editors.EnhancedCustomPropertyEditor;

/**
 *
 * @author  martin.scholl@cismet.de
 */
public class DynamicChildrenSimpleEditor extends javax.swing.JPanel implements 
        EnhancedCustomPropertyEditor // TODO: using depricated api here...
{
    public DynamicChildrenSimpleEditor(final String statement,
            final boolean editable)
    {
        initComponents();
        init();
        edpDynChild.setText(statement);
        edpDynChild.setEditable(editable);
    }
    
    String getStatement()
    {
        return edpDynChild.getText();
    }
    
    private void init()
    {
        edpDynChild.setContentType("text/x-sql"); // NOI18N
        final EditorKit kit =
                JEditorPane.createEditorKitForContentType("text/x-sql");//NOI18N
        kit.install(edpDynChild);
        edpDynChild.setEditorKit(kit);
    }

    @Override
    public Object getPropertyValue() throws IllegalStateException
    {
        return getStatement();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1.setViewportView(edpDynChild);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final transient javax.swing.JEditorPane edpDynChild = new javax.swing.JEditorPane();
    private final transient javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    // End of variables declaration//GEN-END:variables
    
}
