/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.abf.librarysupport.project.customizer;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  1.2
 */
public final class GeneralVisualPanel extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final transient javax.swing.JCheckBox autoreloadCheckbox = new javax.swing.JCheckBox();
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form GeneralVisualPanel.
     */
    public GeneralVisualPanel() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public boolean isAutoReload() {
        return autoreloadCheckbox.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        autoreloadCheckbox.setSelected(true);
        autoreloadCheckbox.setText(org.openide.util.NbBundle.getMessage(
                GeneralVisualPanel.class,
                "GeneralVisualPanel.autoreloadCheckbox.text"));    // NOI18N
        autoreloadCheckbox.setToolTipText(org.openide.util.NbBundle.getMessage(
                GeneralVisualPanel.class,
                "GeneralVisualPanel.autoreloadCheckbox.tooltip")); // NOI18N
        autoreloadCheckbox.setEnabled(false);

        final org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(autoreloadCheckbox).addContainerGap(
                    133,
                    Short.MAX_VALUE)));
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    autoreloadCheckbox,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                    18,
                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap(274, Short.MAX_VALUE)));
    } // </editor-fold>//GEN-END:initComponents
}
