/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.abf.domainserver.project;

import de.cismet.cids.abf.utilities.ProgressIndicatingExecutor;
import org.openide.util.NbBundle;
import org.openide.util.WeakListeners;
import org.openide.windows.WindowManager;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JDialog;

/**
 * Quick and dirty hack, should be refactored asap.
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public class WaitDisconnectDialog extends JDialog {

    //~ Instance fields --------------------------------------------------------

    private final transient ActionListener cancelL;
    private final transient ProgressIndicatingExecutor executor;

    private transient boolean cancelled;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel lblWaitFinished;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form WaitDisconnectDialog.
     *
     * @param  executor  DOCUMENT ME!
     */
    public WaitDisconnectDialog(final ProgressIndicatingExecutor executor) {
        super(WindowManager.getDefault().getMainWindow(), "Disconnecting...");

        this.executor = executor;

        initComponents();

        cancelL = new CancelListener();
        cancelled = false;

        btnCancel.addActionListener(WeakListeners.create(ActionListener.class, cancelL, btnCancel));

        final Thread t = new Thread(new Runnable() {

                    @Override
                    public void run() {
                        while (executor.tasksInProgress()) {
                            try {
                                Thread.sleep(200);
                            } catch (final InterruptedException ex) {
                                // noop
                            }
                        }

                        WaitDisconnectDialog.this.setVisible(false);
                    }
                });
        t.start();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public boolean isCancelled() {
        return cancelled;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        lblWaitFinished = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(343, 29));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblWaitFinished.setText(NbBundle.getMessage(WaitDisconnectDialog.class, "WaitDisconnectDialog.lblWaitFinished.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(lblWaitFinished, gridBagConstraints);

        btnCancel.setText(NbBundle.getMessage(WaitDisconnectDialog.class, "WaitDisconnectDialog.btnCancel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btnCancel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    //~ Inner Classes ----------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private final class CancelListener implements ActionListener {

        //~ Methods ------------------------------------------------------------

        @Override
        public void actionPerformed(final ActionEvent e) {
            cancelled = true;
            WaitDisconnectDialog.this.setVisible(false);
        }
    }
}
